apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    type: frontenddeployment-experimental
    app: frontenddeployment
  name: frontenddeployment-experimental
spec:
  replicas: {{.Values.frontendExperimentalReplicas}}
  selector:
    matchLabels:
      app: frontend
  strategy: {}
  template:
    metadata:
      labels:
        app: frontend
        version: experimental
    spec:
      containers:
      - image: sunishsurendrank/frontend:{{.Values.frontendExperimentalTag}}
        name: frontend
        ports:
        - containerPort: 80

