apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    type: frontenddeployment-experimental
    app: frontenddeployment
  name: frontenddeployment-experimental
spec:
  replicas: {{.Values.frontendExperimentalReplicas}}
  selector:
    matchLabels:
      type: frontend-experimental
  strategy: {}
  template:
    metadata:
      labels:
        app: frontend
        version: frontend-experimental
    spec:
      containers:
      - image: sunishsurendrank/frontend:{{.Values.frontendTag}}
        name: frontend
        ports:
        - containerPort: 80

