
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: ingress-gateway-frontend
spec:
  selector:
    app: istio-ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"

---
kind: VirtualService
apiVersion: networking.istio.io/v1alpha3
metadata:
  name: frontend-virtualservice
  namespace: default
  labels:
    kiali_wizard: request_routing
spec:
  hosts:
    - "*"
  gateways: 
    - ingress-gateway-frontend
  http:
    - route:
        - destination:
            host: frontend-clusterip.default.svc.cluster.local
            subset: original
          weight: 10
        - destination:
            host: frontend-clusterip.default.svc.cluster.local
            subset: experimental
          weight: 90
---
kind: DestinationRule
apiVersion: networking.istio.io/v1alpha3
metadata:
  name: frontend-destinationrule
  namespace: default
  labels:
    kiali_wizard: request_routing
spec:
  host: frontend-clusterip.default.svc.cluster.local
  subsets:
    - labels:
        version: original
      name: original
    - labels:
        version: experimental
      name: experimental
